server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SkillBoostService
    username: ivanmilovanov
    password: ivanmilovanov
    driver-class-name: org.postgresql.Driver

open-ai:
  api-key: ${API_KEY}
  ai-model: gpt-3.5-turbo
  temperature: 0.5
  prompt-role: system
  prompt-message: >
    Сгенерируй строго валидный JSON без лишних полей и комментариев.
    JSON должен содержать одну тему с названием: "%s".
    Добавь ровно 5 уникальных вопросов по этой теме на русском языке.
    Считай, что у тебя есть память: ты уже задавал сотни разных вопросов по этой теме.
    Каждый вопрос должен иметь различный уровень сложности: очень простой, простой, средний, выше среднего, сложный.
    Вопросы должны отличаться по типу: определение, пример, анализ, практическое применение, сравнение понятий.
    К каждому вопросу придумай ровно 3 варианта ответа на русском, содержащих осмысленную информацию.
    Ответы не должны быть примитивными, а должны отражать ключевые аспекты и принципы темы.
    Один из ответов должен быть правильным и иметь значение "isCorrect": true, остальные должны иметь "isCorrect": false.
    Используй только следующие поля: "topic", "questions", "question", "answers", "text", "isCorrect".